import Head from "next/head";
import { Header } from "../components/Header";
import { Footer } from "../components/Footer";
import { SideMenu } from "../components/SideMenu";
import { BreadcrumbsComponent } from "./BreadcrumbsComponent";

export const MainLayout = ({ children }) => {
  return (
    <>
      <Head>
        <title>UniBoost</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Header />
      <SideMenu />
      <BreadcrumbsComponent />
      {children}
      <Footer />
    </>
  );
};
