import Head from "next/head";
import { useEffect } from "react";
import Router from "next/router";

import { MainLayout } from "../components/MainLayout";

export default function Home() {
  useEffect(() => {
    const { pathname } = Router;
    if (pathname == "/lists") {
      Router.push("/lists/products");
    }
  }, []);

  return (
    <MainLayout>
      <Head>
        <title>UniBoost</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
    </MainLayout>
  );
}
